[package]
name = "amg"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
image = "0"
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0"
wasm-bindgen = "0"